### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by JannikSt** [jonguenther/dhbw_wwi16e#1]
I highly suggest to rethink the repository structure.

**Comment by jonguenther** [comment]
We really should! Problem is that we to decide to whether we favour either usability or visibility

**Comment by JannikSt** [comment]
I agree. What does @fkjohn think?

**Comment by fkjohn** [comment]
I think we should clearly mark which files belong to which tasks - that would be a great step to improve usability.

**Comment by jonguenther** [comment]
Thing is that many files reference each other. E.g. `Employee.java` references to `Date.java`, as does `Pet.java` and the other `Employee`-files

**Comment by jonguenther** [comment]
Reworked Strucure: Every task and script gets its own package
