### ISSUE TITLE
Put all Tasks into one folder

### ISSUE THREAD

**Issue by jonguenther** [jonguenther/dhbw_wwi16e#4]
Please put all tasks you create into the `tasks` package. This way people don't have to look for the tasks through all subfolders

**Comment by fkjohn** [comment]
Are we supposed to delete the tasks from the specific package (e.g. move it) or copy them?

**Comment by jonguenther** [comment]
I think it'd be best to copy them and add some comments, because most tasks just simply extend examples from the lectures

**Comment by jonguenther** [comment]
Copied and moved all relevant applied java files to `task` package
